import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../semester_model.dart';
import '../grade_converter.dart';

class PdfService {
  static Future<Uint8List> generatePdf({
    required List<Semester> semesters,
    required double cumulativeGpa,
    required bool isWeighted,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            _buildHeader(cumulativeGpa, isWeighted),
            pw.SizedBox(height: 20),
            ...semesters.map((semester) => _buildSemesterTable(semester, isWeighted)),
            pw.Divider(),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Text(
                'Generated by University GPA Calculator',
                style: const pw.TextStyle(color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(double gpa, bool isWeighted) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.blueGrey50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('University GPA Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              pw.Text(isWeighted ? 'Weighted GPA' : 'Unweighted GPA', style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('Cumulative GPA', style: const pw.TextStyle(fontSize: 12)),
              pw.Text(
                gpa.toStringAsFixed(2),
                style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSemesterTable(Semester semester, bool isWeighted) {
    // Calculate semester headers or stats if needed
    
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(semester.name.toUpperCase(), style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
        pw.SizedBox(height: 5),
        pw.TableHelper.fromTextArray(
          headers: ['Course', 'Credits', 'Type', 'Grade', 'Points'],
          border: null,
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.blue600),
          rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
          cellAlignment: pw.Alignment.centerLeft,
          cellPadding: const pw.EdgeInsets.all(5),
          data: semester.courses.map((course) {
            double points = 0.0;
            if (course.grade != null) {
               points = GradeConverter.convertToPoints(course.grade!);
               if (isWeighted) {
                 if (course.courseType == 'Honors') points += 0.5;
                 if (course.courseType == 'AP') points += 1.0;
               }
            }
            // format
            return [
              course.nameController.text.isNotEmpty ? course.nameController.text : 'Unknown',
              course.creditsController.text,
              course.courseType,
              course.grade ?? '-',
              points.toStringAsFixed(1), // weighted points
            ];
          }).toList(),
        ),
        pw.SizedBox(height: 15),
      ],
    );
  }
}
