import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../semester_model.dart';
import '../grade_converter.dart';

class PdfService {
  static Future<Uint8List> generatePdf({
    required List<Semester> semesters,
    required double cumulativeGpa,
  }) async {
    final pdf = pw.Document();
    final classification = GradeConverter.getDegreeClassification(cumulativeGpa);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            _buildHeader(cumulativeGpa, classification),
            pw.SizedBox(height: 20),
            ...semesters.map((semester) => _buildSemesterTable(semester)),
            pw.Divider(),
            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Text(
                'Generated by University GPA Calculator',
                style: const pw.TextStyle(color: PdfColors.grey),
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(double gpa, String classification) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.blueGrey50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('University Academic Transcript Report', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 4),
              pw.Text('Classification: $classification', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('Cumulative GPA', style: const pw.TextStyle(fontSize: 11)),
              pw.Text(
                gpa.toStringAsFixed(2),
                style: pw.TextStyle(fontSize: 26, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSemesterTable(Semester semester) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(semester.name.toUpperCase(), style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
        pw.SizedBox(height: 5),
        pw.TableHelper.fromTextArray(
          headers: ['Subject / Course', 'Credits', 'Grade', 'Grade Point'],
          border: null,
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.blue600),
          rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
          cellAlignment: pw.Alignment.centerLeft,
          cellPadding: const pw.EdgeInsets.all(6),
          data: semester.courses.map((course) {
            double points = 0.0;
            if (course.grade != null) {
              points = GradeConverter.convertToPoints(course.grade!);
            }
            return [
              course.nameController.text.isNotEmpty ? course.nameController.text : 'Course',
              course.creditsController.text.isNotEmpty ? course.creditsController.text : '0',
              course.grade ?? '-',
              points.toStringAsFixed(2),
            ];
          }).toList(),
        ),
        pw.SizedBox(height: 15),
      ],
    );
  }
}
